version: "3.1"

services:
  
  # Regular Web Server
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8000:80"
      - "443:443" # listen on HTTPS port
    volumes:
       # Main config
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
       - ./nginx/log/:/var/log/nginx/
       # Server blocks config
       - ./nginx/conf.d/:/etc/nginx/conf.d/
       # Serve static content
       - ./website/:/var/www/html/
       # Add SSL
       - ./nginx/certs:/etc/nginx/certs

