version: "3.1"

services:
  
  # network load balancer server + cache
  nlb:
    container_name: nlb
    build: ./nlb
    ports:
      - "8000:80"
    volumes:
       # Main config
       - ./nlb/nginx.conf:/etc/nginx/nginx.conf
       - ./nlb/log/:/var/log/nginx/
       # Server blocks config
       - ./nlb/conf.d/:/etc/nginx/conf.d/
  
  # backend server - instance 1
  nginx1:
    container_name: nginx1
    image: nginx:alpine
    ports:
      - "8001:80"
    volumes:
       # Main config
       - ./nginx1/nginx.conf:/etc/nginx/nginx.conf
       - ./nginx1/log/:/var/log/nginx/
       # Server blocks config
       - ./nginx1/conf.d/:/etc/nginx/conf.d/
       # Serve static content
       - ./website-replica1/:/var/www/html/
      
  # backend server - instance 2
  nginx2:
    container_name: nginx2
    image: nginx:alpine
    ports:
      - "8002:80"
    volumes:
       # Main config
       - ./nginx2/nginx.conf:/etc/nginx/nginx.conf
       - ./nginx2/log/:/var/log/nginx/
       # Server blocks config
       - ./nginx2/conf.d/:/etc/nginx/conf.d/
       # Serve static content
       - ./website-replica2/:/var/www/html/
